In [ ]:
import pandas as pd

df = pd.read_csv("GSAF5(Sheet1-GSAF) (1).csv", encoding='latin1')

df.head()

C:\Users\naila\AppData\Local\Temp\ipykernel_23440\3378033241.py:4: DtypeWarning: Columns (0: Date, 1: Type, 2: Country, 3: State, 4: Location, 5: Activity, 6: Name, 7: Sex, 8: Age, 9: Injury, 10: Fatal Y/N, 11: Time, 12: Species , 13: Source, 14: pdf, 15: href formula, 16: href, 17: Case Number, 18: Case Number.1, 19: Unnamed: 21, 20: Unnamed: 22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("GSAF5(Sheet1-GSAF) (1).csv", encoding='latin1')

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Unnamed: 245,Unnamed: 246,Unnamed: 247,Unnamed: 248,Unnamed: 249,Unnamed: 250,Unnamed: 251,Unnamed: 252,Unnamed: 253,Unnamed: 254
0,14/04,2026.0,UNprovoked,Maldives,Gaafu Alif Atoll,Kooddoo,Swimming,Not stated - on honeymoon,M,?,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3rd April,2026.0,Unprovoked,Australia,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,Oliver Tokic-Bensley,M,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,26th March,2026.0,Unprovoked,Bahamas,Andros Island,Fresh Creek,Swimming,Australian woman,F,22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,25th March,2026.0,Unprovoked,Australia,South Australia,Cape Jaffa Limestone Coast,Diving,Luke Kuhn,M,?,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,22nd-23rd March,2026.0,Unprovoked,Australia,NSW,Little Avalon Beach,Surfing,Unknown,M,30+,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
import pandas as pd

df = pd.read_csv("GSAF5(Sheet1-GSAF) (1).csv", encoding='latin1')

df = df.dropna(axis=1, how='all')

df = df.dropna(axis=0, how='all')

# 4. VER EL RESULTADO
print(f"Ahora el DataFrame tiene {df.shape[1]} columnas y {df.shape[0]} filas.")
df.head()

Ahora el DataFrame tiene 23 columnas y 7087 filas.

C:\Users\naila\AppData\Local\Temp\ipykernel_13248\3708210468.py:4: DtypeWarning: Columns (0: Date, 1: Type, 2: Country, 3: State, 4: Location, 5: Activity, 6: Name, 7: Sex, 8: Age, 9: Injury, 10: Fatal Y/N, 11: Time, 12: Species , 13: Source, 14: pdf, 15: href formula, 16: href, 17: Case Number, 18: Case Number.1, 19: Unnamed: 21, 20: Unnamed: 22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("GSAF5(Sheet1-GSAF) (1).csv", encoding='latin1')

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,14/04,2026.0,UNprovoked,Maldives,Gaafu Alif Atoll,Kooddoo,Swimming,Not stated - on honeymoon,M,?,...,Unknown,The U.S. Sun: Simon De Marchi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3rd April,2026.0,Unprovoked,Australia,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,Oliver Tokic-Bensley,M,16,...,Bronze Whaler,ABC News: The Guardian: Andrew Currie and Bob...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,26th March,2026.0,Unprovoked,Bahamas,Andros Island,Fresh Creek,Swimming,Australian woman,F,22,...,Unknown,WIC News: Melissa Michaelson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,25th March,2026.0,Unprovoked,Australia,South Australia,Cape Jaffa Limestone Coast,Diving,Luke Kuhn,M,?,...,Great White Shark 3.5m (11.5ft),Bob Myatt GSAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,22nd-23rd March,2026.0,Unprovoked,Australia,NSW,Little Avalon Beach,Surfing,Unknown,M,30+,...,Unknown,Melissa Michaelson: Instagram,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
print(len(df))

7087

In [11]:
import pandas as pd

df = pd.read_csv("GSAF5(Sheet1-GSAF) (1).csv", encoding='latin1', low_memory=False)

df.columns = df.columns.str.strip()

columns_i_want= ['Date', 'Year', 'Type', 'Country', 'State', 'Location', 'Activity', 'Name', 'Sex', 'Age', 'Injuries', 'Fatal Y/N', 'Especies','Source']

df = df[df.columns.intersection(columns_i_want)]

df = df.dropna(how='all')
df.head()

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,Fatal Y/N,Source
0,14/04,2026.0,UNprovoked,Maldives,Gaafu Alif Atoll,Kooddoo,Swimming,Not stated - on honeymoon,M,?,N,The U.S. Sun: Simon De Marchi
1,3rd April,2026.0,Unprovoked,Australia,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,Oliver Tokic-Bensley,M,16,N,ABC News: The Guardian: Andrew Currie and Bob...
2,26th March,2026.0,Unprovoked,Bahamas,Andros Island,Fresh Creek,Swimming,Australian woman,F,22,N,WIC News: Melissa Michaelson
3,25th March,2026.0,Unprovoked,Australia,South Australia,Cape Jaffa Limestone Coast,Diving,Luke Kuhn,M,?,N,Bob Myatt GSAF
4,22nd-23rd March,2026.0,Unprovoked,Australia,NSW,Little Avalon Beach,Surfing,Unknown,M,30+,N,Melissa Michaelson: Instagram

In [22]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
7082    False
7083    False
7084    False
7085    False
7086    False
Length: 7087, dtype: bool

In [23]:
df.duplicated().sum()

np.int64(3)

In [13]:
df.columns = df.columns.str.strip().str.lower()
df['type'] = df['type'].str.replace('UNprovoked', 'Unprovoked', case=False)

df['type'] = df['type'].str.lower()
print(df['type'].unique())
df.head()

<StringArray>
[         'unprovoked',            'provoked',        'questionable',
           ' provoked',          'watercraft',        'sea disaster',
                   nan,                   '?',         'unconfirmed',
          'unverified',             'invalid', 'under investigation',
                'boat']
Length: 13, dtype: str

,date,year,type,country,state,location,activity,name,sex,age,fatal y/n,source
0,14/04,2026.0,unprovoked,Maldives,Gaafu Alif Atoll,Kooddoo,Swimming,Not stated - on honeymoon,M,?,N,The U.S. Sun: Simon De Marchi
1,3rd April,2026.0,unprovoked,Australia,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,Oliver Tokic-Bensley,M,16,N,ABC News: The Guardian: Andrew Currie and Bob...
2,26th March,2026.0,unprovoked,Bahamas,Andros Island,Fresh Creek,Swimming,Australian woman,F,22,N,WIC News: Melissa Michaelson
3,25th March,2026.0,unprovoked,Australia,South Australia,Cape Jaffa Limestone Coast,Diving,Luke Kuhn,M,?,N,Bob Myatt GSAF
4,22nd-23rd March,2026.0,unprovoked,Australia,NSW,Little Avalon Beach,Surfing,Unknown,M,30+,N,Melissa Michaelson: Instagram

In [24]:
df.head()

,date,year,type,country,state,location,activity,name,sex,age,fatal y/n,source
0,14/04,2026.0,unprovoked,maldives,gaafu alif atoll,kooddoo,swimming,not stated - on honeymoon,m,Unknown,n,the u.s. sun: simon de marchi
1,3rd april,2026.0,unprovoked,australia,south australia,middleton beach fleurieu peninsula adelaide,surfing,oliver tokic-bensley,m,16,n,abc news: the guardian: andrew currie and bob...
2,26th march,2026.0,unprovoked,bahamas,andros island,fresh creek,swimming,australian woman,f,22,n,wic news: melissa michaelson
3,25th march,2026.0,unprovoked,australia,south australia,cape jaffa limestone coast,diving,luke kuhn,m,Unknown,n,bob myatt gsaf
4,22nd-23rd march,2026.0,unprovoked,australia,nsw,little avalon beach,surfing,Unknown,m,30+,n,melissa michaelson: instagram

In [25]:
df.duplicated().any()

np.True_

In [36]:
df = df.map(lambda s: s.lower() if type(s) == str else s)

values_to_replace = ['?', 'not stated', 'no stated', 'not reported', 'unknown']
df = df.replace(values_to_replace, 'Unknown')

df = df.fillna('unknown')

df.head()

,date,year,type,country,state,location,activity,name,sex,age,fatal y/n,source,gender_mapped
0,14/04,2026.0,unprovoked,maldives,gaafu alif atoll,kooddoo,swimming,not stated - on honeymoon,male,Unknown,n,the u.s. sun: simon de marchi,male
1,3rd april,2026.0,unprovoked,australia,south australia,middleton beach fleurieu peninsula adelaide,surfing,oliver tokic-bensley,male,16,n,abc news: the guardian: andrew currie and bob...,male
2,26th march,2026.0,unprovoked,bahamas,andros island,fresh creek,swimming,australian woman,female,22,n,wic news: melissa michaelson,female
3,25th march,2026.0,unprovoked,australia,south australia,cape jaffa limestone coast,diving,luke kuhn,male,Unknown,n,bob myatt gsaf,male
4,22nd-23rd march,2026.0,unprovoked,australia,nsw,little avalon beach,surfing,Unknown,male,30+,n,melissa michaelson: instagram,male

In [39]:
df['sex'] = df['sex'].replace({'m': 'Male', 'f': 'Female'})

df.head()

,date,year,type,country,state,location,activity,name,sex,age,fatal y/n,source,gender_mapped
0,14/04,2026.0,unprovoked,maldives,gaafu alif atoll,kooddoo,swimming,not stated - on honeymoon,male,Unknown,n,the u.s. sun: simon de marchi,male
1,3rd april,2026.0,unprovoked,australia,south australia,middleton beach fleurieu peninsula adelaide,surfing,oliver tokic-bensley,male,16,n,abc news: the guardian: andrew currie and bob...,male
2,26th march,2026.0,unprovoked,bahamas,andros island,fresh creek,swimming,australian woman,female,22,n,wic news: melissa michaelson,female
3,25th march,2026.0,unprovoked,australia,south australia,cape jaffa limestone coast,diving,luke kuhn,male,Unknown,n,bob myatt gsaf,male
4,22nd-23rd march,2026.0,unprovoked,australia,nsw,little avalon beach,surfing,Unknown,male,30+,n,melissa michaelson: instagram,male

In [42]:
# Borrar una sola columna
df = df.drop('gender_mapped', axis=1)
df.head()

,date,year,type,country,state,location,activity,name,sex,age,fatal y/n,source
0,14/04,2026.0,unprovoked,maldives,gaafu alif atoll,kooddoo,swimming,not stated - on honeymoon,male,Unknown,n,the u.s. sun: simon de marchi
1,3rd april,2026.0,unprovoked,australia,south australia,middleton beach fleurieu peninsula adelaide,surfing,oliver tokic-bensley,male,16,n,abc news: the guardian: andrew currie and bob...
2,26th march,2026.0,unprovoked,bahamas,andros island,fresh creek,swimming,australian woman,female,22,n,wic news: melissa michaelson
3,25th march,2026.0,unprovoked,australia,south australia,cape jaffa limestone coast,diving,luke kuhn,male,Unknown,n,bob myatt gsaf
4,22nd-23rd march,2026.0,unprovoked,australia,nsw,little avalon beach,surfing,Unknown,male,30+,n,melissa michaelson: instagram

In [ ]:
#cambiar fechas 
# He borrado time