In [37]:
import pandas as pd

df = pd.read_csv("GSAF5(Sheet1-GSAF) (1).csv", encoding='latin1')

df = df.dropna(axis=1, how='all')

df = df.dropna(axis=0, how='all')

# 4. VER EL RESULTADO
print(f"Ahora el DataFrame tiene {df.shape[1]} columnas y {df.shape[0]} filas.")
df.head()

C:\Users\naila\AppData\Local\Temp\ipykernel_33912\2723663876.py:3: DtypeWarning: Columns (0: Date, 1: Type, 2: Country, 3: State, 4: Location, 5: Activity, 6: Name, 7: Sex, 8: Age, 9: Injury, 10: Fatal Y/N, 11: Time, 12: Species , 13: Source, 14: pdf, 15: href formula, 16: href, 17: Case Number, 18: Case Number.1, 19: Unnamed: 21, 20: Unnamed: 22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("GSAF5(Sheet1-GSAF) (1).csv", encoding='latin1')

Ahora el DataFrame tiene 23 columnas y 7087 filas.

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,14/04,2026.0,UNprovoked,Maldives,Gaafu Alif Atoll,Kooddoo,Swimming,Not stated - on honeymoon,M,?,...,Unknown,The U.S. Sun: Simon De Marchi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3rd April,2026.0,Unprovoked,Australia,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,Oliver Tokic-Bensley,M,16,...,Bronze Whaler,ABC News: The Guardian: Andrew Currie and Bob...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,26th March,2026.0,Unprovoked,Bahamas,Andros Island,Fresh Creek,Swimming,Australian woman,F,22,...,Unknown,WIC News: Melissa Michaelson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,25th March,2026.0,Unprovoked,Australia,South Australia,Cape Jaffa Limestone Coast,Diving,Luke Kuhn,M,?,...,Great White Shark 3.5m (11.5ft),Bob Myatt GSAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,22nd-23rd March,2026.0,Unprovoked,Australia,NSW,Little Avalon Beach,Surfing,Unknown,M,30+,...,Unknown,Melissa Michaelson: Instagram,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
print(len(df))

7087

In [41]:
import pandas as pd

df = pd.read_csv("GSAF5(Sheet1-GSAF) (1).csv", encoding='latin1', low_memory=False)

df.columns = df.columns.str.strip()

columns_i_want= ['Date', 'Year', 'Type', 'Country', 'State', 'Location', 'Activity', 'Age', 'Injury', 'Fatal Y/N', 'Especies','Source']

df = df[df.columns.intersection(columns_i_want)]

df = df.dropna(how='all')
df.head()

,Date,Year,Type,Country,State,Location,Activity,Age,Injury,Fatal Y/N,Source
0,14/04,2026.0,UNprovoked,Maldives,Gaafu Alif Atoll,Kooddoo,Swimming,?,Leg strpped off flesh later amputated in hospital,N,The U.S. Sun: Simon De Marchi
1,3rd April,2026.0,Unprovoked,Australia,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,16,Bite wound to R ankle,N,ABC News: The Guardian: Andrew Currie and Bob...
2,26th March,2026.0,Unprovoked,Bahamas,Andros Island,Fresh Creek,Swimming,22,Severe injuries to R arm,N,WIC News: Melissa Michaelson
3,25th March,2026.0,Unprovoked,Australia,South Australia,Cape Jaffa Limestone Coast,Diving,?,NaN,N,Bob Myatt GSAF
4,22nd-23rd March,2026.0,Unprovoked,Australia,NSW,Little Avalon Beach,Surfing,30+,Graze injuries R leg and ankle,N,Melissa Michaelson: Instagram

In [39]:
df.columns = df.columns.str.strip().str.lower()
df['type'] = df['type'].str.replace('UNprovoked', 'Unprovoked', case=False)

df['type'] = df['type'].str.lower()
print(df['type'].unique())
df.head()

<StringArray>
[         'unprovoked',            'provoked',        'questionable',
           ' provoked',          'watercraft',        'sea disaster',
                   nan,                   '?',         'unconfirmed',
          'unverified',             'invalid', 'under investigation',
                'boat']
Length: 13, dtype: str

,date,year,type,country,state,location,activity,name,sex,age,fatal y/n,source
0,14/04,2026.0,unprovoked,Maldives,Gaafu Alif Atoll,Kooddoo,Swimming,Not stated - on honeymoon,M,?,N,The U.S. Sun: Simon De Marchi
1,3rd April,2026.0,unprovoked,Australia,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,Oliver Tokic-Bensley,M,16,N,ABC News: The Guardian: Andrew Currie and Bob...
2,26th March,2026.0,unprovoked,Bahamas,Andros Island,Fresh Creek,Swimming,Australian woman,F,22,N,WIC News: Melissa Michaelson
3,25th March,2026.0,unprovoked,Australia,South Australia,Cape Jaffa Limestone Coast,Diving,Luke Kuhn,M,?,N,Bob Myatt GSAF
4,22nd-23rd March,2026.0,unprovoked,Australia,NSW,Little Avalon Beach,Surfing,Unknown,M,30+,N,Melissa Michaelson: Instagram

In [43]:

df.columns = df.columns.str.lower().str.strip()

if 'state' in df.columns:
    unique_states = df['state'].unique()
    print(unique_states)

<StringArray>
[                 'gaafu alif atoll',                   'south australia',
                     'andros island',                               'nsw',
                        'california',                 'western australia',
                        'queensland',                            'noumea',
              'little cayman island',                            'recife',
 ...
               'milne bay  province',                   'island of volos',
                  'amirante islands',               'kadavu island group',
                'toamasina province',                     'riau province',
                      'bikini atoll', 'between new ireland & new britain',
         'ba ria-vung tau  province',                      'moala island']
Length: 947, dtype: str

In [ ]:
df['state'] = df['state'].str.replace('NSW', 'New South Wales', case=False)

df.head()

,date,year,type,country,state,location,activity,age,injury,fatal y/n,source
0,14/04,2026.0,unprovoked,maldives,Gaafu Alif Atoll,kooddoo,swimming,Unknown,leg strpped off flesh later amputated in hospital,n,the u.s. sun: simon de marchi
1,3rd april,2026.0,unprovoked,australia,South Australia,middleton beach fleurieu peninsula adelaide,surfing,16,bite wound to r ankle,n,abc news: the guardian: andrew currie and bob...
2,26th march,2026.0,unprovoked,bahamas,Andros Island,fresh creek,swimming,22,severe injuries to r arm,n,wic news: melissa michaelson
3,25th march,2026.0,unprovoked,australia,South Australia,cape jaffa limestone coast,diving,Unknown,unknown,n,bob myatt gsaf
4,22nd-23rd march,2026.0,unprovoked,australia,New South Wales,little avalon beach,surfing,30+,graze injuries r leg and ankle,n,melissa michaelson: instagram

In [47]:
df['state'] = df['state'].replace('Between New Ireland & New Britain', 'New Ireland / Britain', case=False)

df['state'] = df['state'].str.title()

TypeError: NDFrame.replace() got an unexpected keyword argument 'case'

In [ ]:
values_to_replace = ['NaN']
df = df.replace(values_to_replace, 'Unknown')

df = df.fillna('Unknown')

df.head()

In [35]:
unique_injuries= df['injury'].unique()

inspection_list = pd.Series(unique_injuries).dropna().sort_values()

print(inspection_list.to_string())

KeyError: 'injury'

In [36]:
df['injury']

KeyError: 'injury'

In [48]:
df['injury'] = df['injury'].astype(str).str.strip()

df['injury'] = df['injury'].str.replace(r'\bR\b', 'right', case=False, regex=True)

df['injury'] = df['injury'].str.replace(r'\bL\b', 'left', case=False, regex=True)

df['injury'] = df['injury'].str.lower().str.capitalize()

print(df['injury'].unique()[:10]) # Vemos los primeros 10 para comparar

<StringArray>
['Leg strpped off flesh later amputated in hospital',
                         'Bite wound to right ankle',
                      'Severe injuries to right arm',
                                           'Unknown',
                'Graze injuries right leg and ankle',
                    'Injuries to both legs and feet',
                                    'Minor injuries',
                     'None reported damage to board',
                     'Lacerations elbow and abdomen',
                         'Deep wounds arms and legs']
Length: 10, dtype: str